language: ruby
before_script:
  - ./spec/setup/arangodb.sh
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-1.7.12
  - rbx-2.2.6
env:
  - ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=2.1
matrix:
  allow_failures:
    - rvm: 2.1.0
script: "bundle exec rake ci"
addons:
  code_climate:
    repo_token: 4d49e70568a106875f85f2918698df75118b4a83af20ad57317b10f5fc40d5e0
