language: ruby
before_script:
- "./spec/setup/arangodb.sh"
rvm:
- 1.9.3
- 2.1.5
- 2.2.0
- jruby-1.7.12
env:
- ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=2.4
script: bundle exec rake ci
addons:
  code_climate:
    repo_token: 4d49e70568a106875f85f2918698df75118b4a83af20ad57317b10f5fc40d5e0
notifications:
  slack:
    secure: qx+GdQL63v5xCKi9m+GcEoX8XER9xbRUw7lJVn1CI1tcKLeTerEYoPknUoroCj9IpR3ebXa666L51pMaU0ZCIazefr7YPDTm3gdAIDcPyEUWr2ym2AONzBDpNAQE8o9AF3FAiFI6oZ7VRTxd1KcmvZAwONepyQSZ7tsUC08JfPY=
