language: ruby
before_install:
  - gem install bundler -v '= 1.5.1' # http://changelog.travis-ci.com/post/71633370723/mri-ruby-2-1-0-and-jruby-1-7-9-available
before_script:
  - ./spec/setup/arangodb.sh
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2.2.5
env:
  - ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=1.4
  - ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=2.0
matrix:
  allow_failures:
    - rvm: 2.1.0
script: "bundle exec rake ci"
addons:
  code_climate:
    repo_token: 4d49e70568a106875f85f2918698df75118b4a83af20ad57317b10f5fc40d5e0
