AbcMetricMethodCheck:            { score: 15.0 }
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 400 }
ClassNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 3 }
CyclomaticComplexityMethodCheck: { complexity: 5 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodLineCountCheck:            { line_count: 10 }
MethodNameCheck:
  pattern: !ruby/regexp /^[_a-z<>=\[\]|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/
ModuleLineCountCheck:            { line_count: 500 }
ModuleNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:            { parameter_count: 5 }
