AbcMetricMethodCheck:            { score: 10.0 }
AssignmentInConditionalCheck:    { }
ClassLineCountCheck:             { line_count: 1000 }
ClassNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 1 }
CyclomaticComplexityMethodCheck: { complexity: 5 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodLineCountCheck:            { line_count: 9 }
MethodNameCheck:
  pattern: !ruby/regexp /^[_a-z<>=\[\]|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/
ModuleLineCountCheck:            { line_count: 500 }
ModuleNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:            { parameter_count: 5 }
