AllCops:
  Includes:
    - '../**/*.rake'
  Excludes:
    - '*_spec.rb'
    - '*spec_helper.rb'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Do not force public/protected/private keyword to be indented at the same
# level as the def keyword. My personal preference is to outdent these keywords
# because I think when scanning code it makes it easier to identify the
# sections of code and visually separate them. When the keyword is at the same
# level I think it sort of blends in with the def keywords and makes it harder
# to scan the code and see where the sections are.
AccessControl:
  Enabled: true

HashSyntax:
  Enabled: true

StringLiterals:
  Enabled: true

Void:
  Enabled: true

LineLength:
  Enabled: true
  Max: 120

SpaceAroundBraces:
  Enabled: true

SpaceInsideHashLiteralBraces:
  Enabled: true

AlignParameters:
  Enabled: true

# I don't agree with this
Blocks:
  Enabled: false

SymbolName:
  Enabled: false

NumericLiterals:
  Enabled: true

SpaceInsideBrackets:
  Enabled: true

WordArray:
  Enabled: true

Lambda:
  Enabled: true

RegexpLiteral:
  Enabled: true

# Don't agree
ConstantName:
  Enabled: false

AvoidPerlisms:
  Enabled: true

AvoidPerlBackrefs:
  Enabled: true

TrivialAccessors:
  Enabled: true
  ExactNameMatch: true

Alias:
  Enabled: true

Loop:
  Enabled: true

# Do not agree at all
AndOr:
  Enabled: false

# This is done by YARD Stick
Documentation:
  Enabled: false
